CREATE TABLE VIDEO (
  VID_ID int(11) NOT NULL AUTO_INCREMENT,
  VID_TITLE varchar(50) DEFAULT NULL,
  VID_DESCRIPTION text DEFAULT NULL,
  VID_URL text DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (VID_ID)
);

CREATE TABLE PORTFOLIO_TYPE (
  POT_ID int(11) NOT NULL AUTO_INCREMENT,
  POT_TITLE varchar(50) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (POT_ID)
);

ALTER TABLE PORTIFOLIO
    ADD POT_ID int(11) DEFAULT NULL,
    ADD CONSTRAINT FOREIGN KEY(POT_ID) REFERENCES PORTFOLIO_TYPE(POT_ID);

ALTER TABLE BANNER
    ADD BAN_COLOR varchar(50) DEFAULT NULL;
ALTER TABLE BANNER
    ADD BAN_FONT_COLOR varchar(50) DEFAULT NULL;
ALTER TABLE BANNER
    ADD BAN_ORDER int(11) DEFAULT NULL;