CREATE TABLE PORTFOLIO_TYPE (
  POT_ID int(11) NOT NULL AUTO_INCREMENT,
  POT_TITLE varchar(50) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_at timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (POT_ID)
);

ALTER TABLE PORTIFOLIO
    ADD POT_ID int(11) DEFAULT NULL,
    ADD CONSTRAINT FOREIGN KEY(POT_ID) REFERENCES PORTFOLIO_TYPE(POT_ID);